theme = "dracula"

[editor]
clipboard-provider = "pasteboard"
line-number = "relative"
cursorline = true
auto-save = true
bufferline = "multiple"
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-base-name", "file-modification-indicator", "version-control"]
right = ["diagnostics", "selections", "position", "file-type"]

[keys.normal]
C-y = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh"
R = ":reload"
"esc" = ":sh macism com.apple.keylayout.ABC"

[keys.normal.space]
f = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh"
F = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh"

[keys.insert]
"esc" = ["normal_mode", ":sh /opt/homebrew/bin/macism com.apple.keylayout.ABC"]

